### ISSUE TITLE
watchify : 无法将“watchify”项识别为 cmdlet、函数、脚本文件或可运行程序的名称。请检查名称的拼写，如果包括路径，请确保路径正确，然后再试一次。 所在位置 行:1 字符: 1

### ISSUE THREAD

**Issue by myVictor** [browserify/watchify#363]
在win10运行watchify main.js -o static/bundle.js这个命令报错，报错信息如标题。

**Comment by goto-bus-stop** [comment]
Did you do `npm install -g watchify`? A global install is required to run `watchify` from the command line. The npm bin folder also needs to be in your `PATH` environment variable.

If you did `npm install watchify`, you have a local installation. You can run a local `watchify` by doing:

```
npx watchify main.js -o static/bundle.js
```
