### ISSUE TITLE
Triggers install errors with Node 12 & 13 

### ISSUE THREAD

**Issue by Mattsi-Jansky** [browserify/watchify#374]
Watchify is using an old version of Chokidar which in turn is using an old version of FSEvents that causes the following issue during dependency install: https://github.com/fsevents/fsevents/issues/278

This would probably be resolved by #371

**Comment by ThisIsMissEm** [comment]
This issue currently causes grunt-browserify installs to log a nasty error message to the console, during install; Which in turn affects openpgpjs

**Comment by tybro0103** [comment]
I've been holding out on switching to webpack, but damn...

**Comment by smhg** [comment]
@goto-bus-stop please let us know if/how we can help. A browserify setup (which includes watchify) is so much more maintainable than webpack.

**Comment by sseide** [comment]
add pr #378 with newer `chokidar` version as well as corresponding `anymatch` update that should fix it as well.
Main problem here with newer chokidar version seems to be the minimum Nodejs 8.x (EOL) requirement?!?

**Comment by goto-bus-stop** [comment]
should be good in 📦 4.0.0, thanks for the reports & PRs!
