### ISSUE TITLE
SOLVED, DISREGARD :)  parsing error when creating bundle.js

### ISSUE THREAD

**Issue by ZonaKyle** [browserify/watchify#376]
Watchify is creating bundle.js with this error below for me.  I've listed my Github to review.  Thanks if anyone can help!

bundle.js error:
console.error("Error: Parsing file C:\\Users\\kylea\\OneDrive\\Desktop\\FullStack Tutorial Files\\HTML Files\\scratch-vc-app\\public\\main.js: Shorthand property assignments are valid only in destructuring patterns (15:84)");

my files:
https://github.com/ZonaKyle/scratch-vc-app

**Comment by goto-bus-stop** [comment]
For future googlers, the cause was this line:
https://github.com/ZonaKyle/scratch-vc-app/blob/92e70a726c77c701b27decb104df3e41d3eaab3a/public/main.js#L15
which uses `stream=stream` inside an object instead of `stream: stream`.
